#!/usr/bin/env python3
"""
Utility script to read and inspect binary .dat files generated by the YexcphPP workflow.

This script demonstrates how to load binary data from files like 'excph.dat',
'A_exc.dat', etc., and reshape them into their correct multi-dimensional
NumPy array format.

Usage:
    # To inspect the exciton-phonon coupling matrix:
    python read_binary_data.py excph.dat

    # To inspect the exciton wavefunctions:
    python read_binary_data.py A_exc.dat

    # To inspect the electron-phonon matrix:
    python read_binary_data.py g_elph.dat
"""

import numpy as np
import os
import sys
import argparse

# Add src directory to path to import parameters
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from common.param import p

def get_file_info(filename):
    """
    Returns the expected shape and data type for a given binary file.
    """
    # This dictionary maps filenames to their properties.
    # The shape uses the parameters from the 'p' object.
    file_map = {
        'excph.dat': {
            'shape': (p.N_Q, p.N_q, p.alpha, p.beta, p.nmodes),
            'dtype': np.complex64,
            'description': 'Exciton-Phonon Coupling Matrix (G)'
        },
        'excph2.dat': {
            'shape': (p.N_Q, p.N_q, p.alpha, p.beta, p.nmodes),
            'dtype': np.float32,
            'description': 'Squared Magnitude of Exciton-Phonon Coupling Matrix (|G|^2)'
        },
        'A_exc.dat': {
            'shape': (p.N_Q, p.beta, p.N_k, p.N_v, p.N_c),
            'dtype': np.complex64,
            'description': 'Exciton Wavefunctions (A_exc)'
        },
        'exc_freq.dat': {
            'shape': (p.N_Q, p.beta),
            'dtype': np.float32,
            'description': 'Exciton Frequencies'
        },
        'exc_freq_deg.dat': {
            'shape': (p.N_Q, p.beta),
            'dtype': np.float32,
            'description': 'Degenerate Exciton Frequencies'
        },
        'g_elph.dat': {
            'shape': (p.N_Q, p.N_k, p.N_v + p.N_c, p.N_v + p.N_c, p.nmodes),
            'dtype': np.complex64,
            'description': 'Electron-Phonon Coupling Matrix (g_elph)'
        },
        'ph_freq.dat': {
            'shape': (p.N_Q, p.nmodes),
            'dtype': np.float32,
            'description': 'Phonon Frequencies'
        },
    }
    return file_map.get(os.path.basename(filename))

def read_and_inspect(filepath):
    """
    Reads a binary file, reshapes it, and prints inspection information.
    """
    if not os.path.exists(filepath):
        print(f"Error: File not found at '{filepath}'")
        return

    file_info = get_file_info(filepath)
    if not file_info:
        print(f"Warning: No shape/dtype information found for '{os.path.basename(filepath)}'.")
        print("   Please add its details to the 'file_map' in this script.")
        return

    shape = file_info['shape']
    dtype = file_info['dtype']
    description = file_info['description']

    print("=" * 70)
    print(f"Inspecting File: {os.path.basename(filepath)}")
    print(f"Description: {description}")
    print("=" * 70)

    try:
        # Load the raw binary data from the file
        data_flat = np.fromfile(filepath, dtype=dtype)

        print(f"  - File Path: {filepath}")
        print(f"  - Data Type (dtype): {dtype}")
        print(f"  - Total elements in file: {data_flat.size}")

        # Reshape the flat array into its proper multi-dimensional shape
        expected_elements = np.prod(shape)
        print(f"  - Expected shape: {shape}")
        print(f"  - Expected elements from shape: {expected_elements}")

        if data_flat.size != expected_elements:
            print(f"  - FATAL MISMATCH: The number of elements in the file ({data_flat.size})")
            print(f"                     does not match the expected number from the shape ({expected_elements}).")
            print( "  - This likely means the parameters in 'config.yml' or 'src/common/param.py'")
            print( "    do not match the parameters used to generate this file.")
            return

        data_reshaped = data_flat.reshape(shape)
        print("  - Reshape successful!")
        print("-" * 70)

        # Print a sample of the data
        print("Data Sample (first element):")
        print(data_reshaped.flat[0])

        print("\nData Sample (a corner element from the multi-dimensional array):")
        # Accessing an element using indices, e.g., at (0, 0, ..., 0)
        corner_element = data_reshaped[(0,) * data_reshaped.ndim]
        print(corner_element)

        print("\n" + "=" * 70)
        print("Inspection Complete")
        print("=" * 70)

    except Exception as e:
        print(f"An error occurred during inspection: {e}")

def main():
    """
    Main function to parse arguments and initiate the inspection.
    """
    parser = argparse.ArgumentParser(
        description="A utility to read and inspect binary .dat files from the YexcphPP workflow."
    )
    parser.add_argument(
        'filename',
        help="The name of the binary file to inspect (e.g., 'excph.dat'). The script will search for it in the output directory."
    )
    parser.add_argument(
        '-c', '--config',
        default='config.yml',
        help="Path to the configuration file to load parameters from (default: config.yml)."
    )
    args = parser.parse_args()

    # Load parameters from the specified config file
    if not os.path.exists(args.config):
        print(f"Config file '{args.config}' not found.")
        sys.exit(1)
    p.read_input_parameters(args.config)

    # The output directory is built relative to the working_dir from the config
    output_dir = p.output_data_dir
    filepath = os.path.join(output_dir, args.filename)

    read_and_inspect(filepath)

if __name__ == "__main__":
    main()
